config/routes.rb
Rails.application.routes.draw do
  # get 'contacts/index'
  resources :contacts

  root 'contacts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :group
	# add validation
	validates :name, :email, :phone, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:edit, :update, :destroy]

  def index
  	if params[:group_id]
      @group = Group.find(params[:group_id])
      @contacts = @group.contacts.paginate(page: params[:page], per_page: 10)
    else
      @contacts = Contact.paginate(page: params[:page], per_page: 10)
    end
  end

  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(contact_params)
    if @contact.save
  		flash[:success] = "Successfully created new contact"
  		redirect_to contacts_path
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:success] = "Successfully update contact"
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact.destroy
    flash[:success] = "Successfully deleted contact"
    redirect_to contacts_path
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])    
  end

  def contact_params
  	params.require(:contact).permit(:name, :email, :company, :address, :phone, :avatar, :group_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact, html: { multipart: true} do |f| %>

	<div class="panel-body">
		
		<% if @contact.errors.any? %>
			<div class="row">
				<div class="col-md-12">
					<div class="alert alert-danger">
						<h3>Please correct this following errors:</h3>
						<ul>
							<% @contact.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			<% end %>

		<div class="form-horizontal">
			<div class="row">
				<div class="col-md-8">
					<div class="form-group">
						<%= f.label :name, class: "control-label col-md-3" %>
						<div class="col-md-8">
							<%= f.text_field :name, class:"form-control" %>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :company, class: "control-label col-md-3" %>
						<div class="col-md-8">
							<%= f.text_field :company, class:"form-control" %>
						</div>							
					</div>

					<div class="form-group">
						<%= f.label :email, class: "control-label col-md-3" %>
						<div class="col-md-8">
							<%= f.text_field :email, class:"form-control" %>
						</div>
					</div>					

					<div class="form-group">
						<%= f.label :phone, class: "control-label col-md-3" %>
						<div class="col-md-8">
							<%= f.text_field :phone, class:"form-control" %>
						</div>
					</div>										

					<div class="form-group">
						<%= f.label :address, class: "control-label col-md-3" %>
						<div class="col-md-8">
							<%= f.text_area :address, class:"form-control" %>
						</div>
					</div>															

					<div class="form-group">
						<label for="group" class="control-label col-md-3">Group</label>
						<div class="col-md-5">
							<%= f.collection_select :group_id, Group.all, :id, :name, { prompt: "Select Group" }, class: "form-control" %>

<!--
							<select type="text" name="group" id="group" class="form-control">
								<option value="">Select group</option>
								<option value="1">Family</option>
								<option value="2">Friend</option>						
								<option value="3">Other</option>						
-->

							</select>							
						</div>
						<div class="col-md-3">
							<a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
						</div>
					</div>																				
					<div class="form-group" id="add-new-group">
						<div class="col-md-offset-3 col-md-8">
							<div class="input-group">
								<input type="text" name="new_group" id="new_group" class="form-control">
								<span class="input-group-btn">
									<a href="#" class="btn btn-default">
										<i class="glyphicon glyphicon-ok"></i>
									</a>
								</span>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="fileinput fileimput-new" data-provides="fileinput">
						<div class="fileimput-new thumbnail" style="width: 150px; height: 150px;">
							<% image_tag @contact.avatar.url(:medium) %>
						</div>
						<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 150px; max-height: 150px;"></div>
						<div class="text-center">
							<span class="btn btn-default btn-file">
								<span class="fileinput-new">Chose Photo</span>
								<span class="fileinput-exists">Change</span>
								<%= f.file_field :avatar %>
							</span>
							<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-footer">
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-offset-3 col-md-6">
						<button type="submit" class="btn btn-primary">Save</button>
						
						<%= link_to "Cancel", contacts_path, class: "btn btn-default" %>
					</div>
				</div>
			</div>
		</div>
	</div>

<% end %>

app/views/contacts/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Edit</strong>
	</div>

	<%= render 'form' %>

</div>

app/views/contacts/index.html.erb
<div class="panel panel-default">
	<table class="table">
		
		<% @contacts.each do |contact| %>

		<tr>
			<td class="middle">
				<div class="media">
					<div class="media-left">
						<a href="#">
							<%= image_tag contact.avatar.url(:thumb), class: "media-object" %>
						</a>
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= contact.name %></h4>
						<address>
							<strong><%= contact.company %></strong>
							<br>
							<%= contact.email %>
						</address>
					</div>
				</div>
			</td>
			<td width="100" class="middle">
				<div>
					<%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
						<i class="glyphicon glyphicon-edit"></i>						
					<% end %>
					
					<%= link_to contact_path(contact), :method => :delete, class: "btn btn-circle btn-default btn-xs", title: "Delete", data: {confirm: "Are you sure?"} do %>
						<i class="glyphicon glyphicon-remove"></i>
					<% end %>					
				</div>
			</td>
		</tr>

		<% end %>

	</table>
</div>

<div class="text-center">
	<%= will_paginate %>
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Add Contact</strong>
	</div>

	<%= render 'form' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<!-- navbar -->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toogle collapsed" data-toogle="collapse" data-target="#navbar-collapse" aria-expanded="false">
					<span class="sr-only">Toogle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<%= link_to "My contact", root_path, class: "navbar-brand text-uppercase" %>

			</div>

			<!-- /. navbar-header -->
			<div class="collapse navbar-collapse" id="navbar-collapse">
				<div class="nav navbar-right navbar-btn">
					<%= link_to new_contact_path, class: "btn btn-default" do %>
						<i class="glyphicon hlyphicon-plus"></i>
						Add Contact
					<% end %>
				</div>
			</div>
		</div>
	</nav>

	<!-- content -->
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="list-group">
					<!-- set active links -->
					<% active = params[:group_id] == nil ? 'active' : '' %>


					<%= link_to contacts_path, class: "list-group-item #{active}" do %>
							All Contacts<span class="badge"><%= Contact.count %></span>
					<% end %>

					<% Group.all.each do |group| %>
						<% active = params[:group_id].to_i == group.id ? 'active' : '' %>					
						<%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
							<%= group.name %><span class="badge"><%= group.contacts.count %></span>
						<% end %>
					<% end %>

				</div>
			</div> <!-- /.col-md-3 -->
			
			<div classs="col-md-9">
    			
				<% flash.each do |type, message| %>
					<% content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
						<%= message %>
						</button>
					<% end %>
				<% end %>
    			
    			<%= yield %>
			
			</div>
		</div>
	</div>
</body>
</html>